# Generated by Django 4.2.3 on 2023-07-26 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='date',
            field=models.DateField(verbose_name='%d-%m-%Y'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='sign',
            field=models.CharField(max_length=100),
        ),
    ]
